app/urls.py
from django.urls import path, include

from app.views import (
    TaskCreateView,
    TaskUpdateView,
    TaskListView,
    TaskDeleteView,
    TaskDetailView,
    change_task_status,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TagListView,

)

urlpatterns = [
    path(
        "",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/change/",
        change_task_status,
        name="task-change"
    ),

    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]

app_name = "app"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app"))
]

app/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ["completed", "-created"]

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name

app/forms.py
from django import forms

from app.models import Task, Tag


class TaskCreateForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(
        widget=forms.TextInput(attrs={'type': 'datetime-local'}),
        required=False
    )
    content = forms.CharField(max_length=255)

    class Meta:
        model = Task
        fields = "__all__"

app/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from app.forms import TaskCreateForm
from app.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    context_object_name = "task_list"
    paginate_by = 2


class TaskDetailView(generic.DetailView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("app:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("app:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("app:task-list")


def change_task_status(request, pk):
    task = Task.objects.get(pk=pk)
    task.completed = not task.completed
    task.save()

    return HttpResponseRedirect(reverse("app:task-list"))


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("app:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("app:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("app:tag-list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 10

templates/app/index.html
{% extends "base.html" %}

{% block title %}TODO - Home{% endblock %}

{% block content %}
<div class="container">
  <h1>TODO list
    <button style="float: end" onclick="window.location.href='{% url 'app:task-create' %}';" type="button"
            class="btn btn-success">
      Add task
    </button>
  </h1>
  <br>
  {% for task in task_list %}
    <p><strong>{{ task|truncatechars:20 }}
      {% if task.completed %}
        <span class="text-success">Done</span>
        <button style="float: right" onclick="window.location.href='{% url 'app:task-change' pk=task.id %}';" type="button"
            class="btn btn-secondary">
      Undo
    </button>
      {% else %}
        <span class="text-danger">Not done</span>
        <button style="float: right" onclick="window.location.href='{% url 'app:task-change' pk=task.id %}';" type="button"
            class="btn btn-success">
      Complete
    </button>
      {% endif %}
    </strong>

    </p>
    <p>Created: {{ task.created }}
      {% if task.deadline %}
        <span class="text-danger">Deadline: {{ task.deadline }}</span>
      {% endif %}
    </p>
    <p class="text-muted">
      <strong>Tags: {{ task.tags.all|join:" " }}</strong>
    </p>
    <p>
      <a class="text-primary" href="{% url 'app:task-detail' pk=task.id %}">detail</a>
      <a class="text-warning" href="{% url 'app:task-update' pk=task.id %}">Update</a>
      <a class="text-danger" href="{% url 'app:task-delete' pk=task.id %}">Delete</a>
    </p>
    <hr>
    {% empty %}
    <p>There are no task yet</p>
  {% endfor %}
</div>
{% endblock %}

templates/app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete confirmation</h1>
  <p>You are trying to delete tag: <strong>{{ tag }}</strong></p>
  <h3>Are you sure?</h3>
  <p>This process cannot be reversed</p>
<div>
  {% include "includes/confirmation_form.html" %}

  <button onclick="window.location.href='{% url 'app:tag-list' %}';" type="button"
              class="btn btn-success">
        No, back to the tag list
      </button>
<button onclick="window.location.href='{% url 'app:tag-update' pk=tag.id %}';" type="button"
              class="btn btn-warning">
        No, edit tag
      </button>
</div>
{% endblock %}

templates/app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} tag</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>

{% endblock %}

templates/app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags
    <button style="float: end" onclick="window.location.href='{% url 'app:tag-create' %}';" type="button"
            class="btn btn-success">
      Add tag
    </button>
  </h1>
  <br>

  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for tag in tag_list %}
      <tr class="table-default">
      <td>{{ tag.name }}</td>
      <td>
        <button style="float: none" onclick="window.location.href='{% url 'app:tag-update' pk=tag.id %}';" type="button"
                class="btn btn-warning">
          Update
        </button>
      </td>
      <td>
        <button style="float: none" onclick="window.location.href='{% url 'app:tag-delete' pk=tag.id %}';" type="button"
                class="btn btn-danger">
          Delete
        </button>
      </td>
    {% empty %}
      <p>There are no tags yet</p>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete confirmation</h1>
  <p>You are trying to delete task: <strong>{{ task|truncatechars:20 }}</strong></p>
  <p>Task was created <strong>{{ task.created }}</strong> and <strong>{{ task.completed|yesno:"completed, not completed" }}</strong></p>
  <h3>Are you sure?</h3>
  <p>This process cannot be reversed</p>
<div>
  {% include "includes/confirmation_form.html" %}

  <button onclick="window.location.href='{% url 'app:index' %}';" type="button"
              class="btn btn-success">
        No, back to the task list
      </button>
<button onclick="window.location.href='{% url 'app:task-detail' pk=task.id %}';" type="button"
              class="btn btn-success">
        No, show task detail
      </button>
</div>
{% endblock %}

templates/app/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Task detail</h1>
  <br>
  <p><strong class="text-muted">Id: </strong>{{ task.id }}</p>
  <p><strong class="text-muted">Created: </strong>{{ task.created }}</p>
  <p><strong class="text-muted">Deadline: </strong>{{ task.deadline }}</p>
  <p><strong class="text-muted">Completed: </strong>{{ task.completed|yesno:"Yes, No" }}</p>

  <hr>
  <h4><strong>Content:</strong></h4>
  <p>{{ task.content }}</p>
{% endblock %}

templates/app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} task</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>

{% endblock %}

templates/app/task_list.html
{% extends "base.html" %}

{% block title %}TODO - Home{% endblock %}

{% block content %}
<div class="container">
  <h1>TODO list
    <button style="float: end" onclick="window.location.href='{% url 'app:task-create' %}';" type="button"
            class="btn btn-success">
      Add task
    </button>
  </h1>
  <br>
  {% for task in task_list %}
    <p><strong>{{ task|truncatechars:20 }}
      {% if task.completed %}
        <span class="text-success">Done</span>
        <button style="float: right" onclick="window.location.href='{% url 'app:task-change' pk=task.id %}';" type="button"
            class="btn btn-secondary">
      Undo
    </button>
      {% else %}
        <span class="text-danger">Not done</span>
        <button style="float: right" onclick="window.location.href='{% url 'app:task-change' pk=task.id %}';" type="button"
            class="btn btn-success">
      Complete
    </button>
      {% endif %}
    </strong>

    </p>
    <p>Created: {{ task.created }}
      {% if task.deadline %}
        <span class="text-danger">Deadline: {{ task.deadline }}</span>
      {% endif %}
    </p>
    <p class="text-muted">
      <strong>Tags: {{ task.tags.all|join:" " }}</strong>
    </p>
    <p>
      <a class="text-primary" href="{% url 'app:task-detail' pk=task.id %}">detail</a>
      <a class="text-warning" href="{% url 'app:task-update' pk=task.id %}">Update</a>
      <a class="text-danger" href="{% url 'app:task-delete' pk=task.id %}">Delete</a>
    </p>
    <hr>
    {% empty %}
    <p>There are no task yet</p>
  {% endfor %}
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}ToDo list{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="content-fluid">

  <div class="row">

    {% block sidebar %}
      {% include "includes/sidebar.html" %}
    {% endblock %}

    <div class="col-md">
      {% block content %}

      {% endblock %}

    {% block pagination %}
      {% include "includes/paginations.html" %}
    {% endblock %}
    </div>
  </div>
</div>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

</body>
</html>

templates/includes/confirmation_form.html
<form action="" method="POST" style="display: inline">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger">
</form>

templates/includes/paginations.html
{% if is_paginated %}
  <ul class="pagination d-flex justify-content-center"">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div style="width: 185px" class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
  <p class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <svg class="bi me-2" width="40" height="32"></svg>
    <span class="fs-4">ToDo</span>
  </p>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="{% url 'app:task-list' %}" class="nav-link text-white" aria-current="page">
        <svg class="bi me-2" width="16" height="16"></svg>
        Home
      </a>
    </li>
    <li>
      <a href="{% url 'app:tag-list' %}" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16"></svg>
        Tags
      </a>
    </li>
  </ul>

</div>